_schema: _schema
source: /
paths:
  uploads: uploads
  static: ''
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Asia/Tehran
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
